### PR TITLE
Remove in-testsuite? requests from "To Nag" view

### PR DESCRIPTION
**Pull request by mounirlamouri**
This includes another commit because I forgot to create a branch for my first patch. Thank you git for being such a pain...

### CODE REVIEW

**Comment by harthur** [comment]
I don't know much about that flag, why is it bad to show if someone is requesting that flag of you?

**Comment by mounirlamouri** [comment]
Argh, I feel bad about the lag here. This flag doesn't have any assignee so you can't request it to someone and no one can request it to you.

The meaning of this flag is the following:
- \- : no test needed, like refactoring, code cleanup, build changes, etc.
- \+ : tested
- ? : no tests (but obviously, needed)

**Comment by harthur** [comment]
Alright, I removed any flags from the To Nag view that don't have a requestee in [c6fe27b](https://github.com/harthur/bugzilla-todos/commit/c6fe27b886984e4b6e74e92adc7b252eb5b07e0f). This includes in-testsuite. Let me know if you think that's a bad idea.

**Comment by mounirlamouri** [comment]
Does that mean that the approvals will no longer show up there?

**Comment by harthur** [comment]
I don't think they show up now. Do you think those should show up?

**Comment by mounirlamouri** [comment]
> I don't think they show up now. Do you think those should show up?

It woudn't hurt, yes. I would probably just make "in-testsuite" a hidden by default. It could actually be an option. Some people might care but I have a hard time to believe that.

**Pull request closed without merging**
