### PR TITLE
Add package.json. Fixes #8.

### LINKED ISSUE #8: have a package.json or makefile or some way of getting deps installed automatically
just cloned

tried to run server

don't have connect

do I install connect globally? what version?

etc etc

### PR DESCRIPTION
**Pull request by nikhilm**
I hope the version number is correct.

This also allows bugzilla-todos to be started using `npm start`.

### CODE REVIEW

**Comment by nikhilm** [comment]
Did not think that entry through. I don't expect breaking changes for such a simple API at least until 3.0.

**Comment by harthur** [comment]
Honestly, safer to stick with leeway in the patch number.

**Comment by nikhilm** [comment]
Should I go with >=2.0.0 <3.0.0 then?

**Comment by harthur** [comment]
Ah no, stick with  `"connect": "~2.8.4"`, that will do `2.8.4` to `< 2.9` I believe.

**Comment by harthur** [comment]
Thanks for all the PRs!

**Pull request merged**
